name: Create Pre-Release on Master Push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Get version from build.gradle
        id: get_version
        run: |
          VERSION=$(./gradlew -q printVersion)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Get Commit hash
        id: get_commit_hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create GitHub release
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}-SNAPSHOT-${{ env.COMMIT_HASH }}
          body: "This is a pre-release for version ${{ env.VERSION }}."
          draft: false
          prerelease: true